name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
